import Ember from 'ember';

export default Ember.Controller.extend({
  tags: [
    "American Traditional",
    "anatomical",
    "anchor",
    "animal",
    "asian inspired",
    "bird",
    "black and gray",
    "black line",
    "blackwork",
    "botanical",
    "color",
    "comic",
    "cover up",
    "dot work",
    "egyptian inspired",
    "eye",
    "fine art inspired",
    "floral",
    "food & drink",
    "geometric",
    "grateful dead",
    "heart",
    "illustration",
    "insect",
    "knotwork",
    "lettering",
    "mandala",
    "native american inspired",
    "nautical",
    "ocean",
    "patriotic",
    "pin up",
    "portrait",
    "quirky",
    "realism",
    "religious",
    "sci fi",
    "science",
    "skull",
    "space",
    "sports",
    "tiny",
    "trash polka",
    "tree"
  ]
});
